version: "1.0"
info:
  model: int-scaffold
packages:
- name: ArHe_DevProject
  gitServerName: ArHe_GitHub
  gitUrl: https://github.com/ahbelisario
  gitUsername: ahbelisario
  gitBranch: main
services:
- serviceName: project.arhe_dev.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.operations.actions:RetreiveCustCredit
  packages:
  - name: ArHe_DevProject
    version: "1.0"
- serviceName: project.arhe_dev.integrations:APICaller
  packages:
  - name: ArHe_DevProject
    version: "1.0"
- serviceName: pub.client:http
  packages:
  - name: WmPublic
    version: 11.1.0.0.2064
- serviceName: pub.json:jsonStreamToDocument
  packages:
  - name: WmPublic
    version: 11.1.0.0.2064
- serviceName: pub.flow:getLastFailureCaught
  packages:
  - name: WmPublic
    version: 11.1.0.0.2064
- serviceName: pub.string:indexOf
  packages:
  - name: WmPublic
    version: 11.1.0.0.2064
- serviceName: project.arhe_dev.integrations:RetreiveCreditApproval
  packages:
  - name: ArHe_DevProject
    version: "1.0"
